### ISSUE TITLE
Performing GMM is time-consuming

### ISSUE THREAD

**Issue by zwx8981** [cientgu/GIQA#10]
Hi, it seems that performing GMM on all 70000 images of FFHQ is quite time-consuming. Could you tell me how long did you get the resulting GMM model on FFHQ ?

**Comment by cientgu** [comment]
Good question. It's really time-consuming because the EM is computed on the CPU instead of the GPU. To me, it cost about 1-1.5 day. The time depends on 1) what CPU you use, 2) the number of kernels in your GMM model  3) the feature dimension.  
You may apply a PCA rate to decrease the channel from 2048 to about 700. Also, you may directly apply this GMM70-FFHQ model (https://drive.google.com/file/d/1TjEPTNKpai236cFOotiwYE7cVRuGNzng/view?usp=sharing).
Hope it may help you.

**Comment by zwx8981** [comment]
Thanks for your quick reply!
